<?php

namespace App\Controller;

use App\Entity\School;
use App\Entity\Session;
use App\Entity\Student;
use App\Entity\Training;
use App\Form\UploadPicture;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

class ProfileController extends AbstractController
{

    /**
     * @Route("/profile/{idStudent}", name="profile")
     */
    public function getInfoStudent($idStudent)
    {
        $reqUser = $this->getDoctrine()->getRepository(Student::Class);
        $user = $reqUser->find($idStudent);
        $idUser = $user->getId();
        if($idUser == $this->getUser()->getId()):
            return $this->render("myProfile.html.twig", ["user" => $user]);
        else:
            return $this->render("viewProfile.html.twig", ["user" => $user]);
        endif;
    }

    /**
     * @Route("/myProfile/{idStudent}", name="profile")
     */
    public function viewMyProfile($idStudent)
    {
        $reqUser = $this->getDoctrine()->getRepository(Student::Class);
        $user = $reqUser->find($idStudent);
        $idUser = $user->getId();
        return $this->render("myProfile.html.twig", ["user" => $user]);
    }


    /**
     * @Route("/accueil/uploadPicture", name="uploadPicture")
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function uploadPicture(Request $request)
    {
        $repository = $this->getDoctrine()->getRepository(Student::class);
        /** @var Student $user */
        $student = $repository->find($this->getUser()->getId());

        $form = $this->createForm(UploadPicture::class, $student);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid())
        {

            /** @var UploadedFile $file */
            $file = $student->getAvatar();
            $fileName = $this->generateUniqueFileName() . '.' . $file->guessExtension();

            try
            {
                $file->move(
                    $this->getParameter('avatar_directory'),
                    $fileName
                );
            }
            catch (FileException $e)
            {
                // TODO Gérer les erreurs
            }

            $student->setAvatar($fileName);

            $em = $this->getDoctrine()->getManager();
            $em->persist($student);
            $em->flush();

            return $this->redirect($this->generateUrl('HomeController'));

        }

        return $this->render(
            "uploadPicture.html.twig",
            [
                'form' => $form->createView(),
                'user' => $this->getUser(),
            ]
        );
    }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }

    /**
     * Permet d'ajouter la séance idSession à l'utilisateur connecté
     * @Route("/accueil/addSession/{idSession}", name="AddSession")
     * @param $idSession
     */
    public function addSession($idSession)
    {
        //TODO : Gérer les erreurs

        /** @var Student $student */
        $student = $this->getUser();
        /** @var Session $listeSession */
        $listeSession = $student->getSessionid();

        $tmp = array();
        $listeSessionEtudiant = array();

        // On parcourt les séances auxquelles l'utilisateur est déjà inscrit
        foreach($listeSession as $session)
        {
            // On ajoute les séances
            array_push($tmp, $session->getId());
        }
        
        foreach ($tmp as $ss)
        {
            // On ajoute les ID des sessions
            array_push($listeSessionEtudiant, $ss);
        }

        if(in_array($idSession,$listeSessionEtudiant))
        {
            die("c'est déjà dans ton agenda");
        }
        else
        {
            $repository = $this->getDoctrine()->getRepository(Session::class);
            $session = $repository->find($idSession);
            $student->addSessionid($session);
            $em = $this->getDoctrine()->getManager();
            $em->persist($student);
            $em->flush();
            die("Ajouté dans ton agenda !");
        }

    }

}